// Audit action types for the Chore-Ganizer application

export const AUDIT_ACTIONS = {
  // Auth actions
  USER_LOGIN: 'USER_LOGIN',
  USER_LOGOUT: 'USER_LOGOUT',
  USER_LOGIN_FAILED: 'USER_LOGIN_FAILED',
  
  // User management
  USER_CREATED: 'USER_CREATED',
  USER_DELETED: 'USER_DELETED',
  USER_UPDATED: 'USER_UPDATED',
  PASSWORD_CHANGED: 'PASSWORD_CHANGED',
  ROLE_CHANGED: 'ROLE_CHANGED',
  
  // Chore templates
  CHORE_TEMPLATE_CREATED: 'CHORE_TEMPLATE_CREATED',
  CHORE_TEMPLATE_DELETED: 'CHORE_TEMPLATE_DELETED',
  CHORE_TEMPLATE_UPDATED: 'CHORE_TEMPLATE_UPDATED',
  
  // Chore assignments (non-recurring)
  CHORE_ASSIGNED: 'CHORE_ASSIGNED',
  CHORE_COMPLETED: 'CHORE_COMPLETED',
  CHORE_DELETED: 'CHORE_DELETED',
  CHORE_UPDATED: 'CHORE_UPDATED',
  
  // Recurring chores
  RECURRING_CHORE_CREATED: 'RECURRING_CHORE_CREATED',
  RECURRING_CHORE_UPDATED: 'RECURRING_CHORE_UPDATED',
  RECURRING_CHORE_DELETED: 'RECURRING_CHORE_DELETED',
  RECURRING_CHORE_SKIPPED: 'RECURRING_CHORE_SKIPPED',
  RECURRING_CHORE_UNSKIPPED: 'RECURRING_CHORE_UNSKIPPED',
  RECURRING_CHORE_COMPLETED: 'RECURRING_CHORE_COMPLETED',
  
  // Pocket money
  PAYOUT_CREATED: 'PAYOUT_CREATED',
  PAYOUT_UPDATED: 'PAYOUT_UPDATED',
  PAYOUT_CANCELLED: 'PAYOUT_CANCELLED',
  POINTS_BONUS_ADDED: 'POINTS_BONUS_ADDED',
  POINTS_DEDUCTION_ADDED: 'POINTS_DEDUCTION_ADDED',
  POINTS_ADJUSTMENT: 'POINTS_ADJUSTMENT',
  
  // Family settings
  FAMILY_SETTINGS_UPDATED: 'FAMILY_SETTINGS_UPDATED',
  POCKET_MONEY_CONFIG_UPDATED: 'POCKET_MONEY_CONFIG_UPDATED',
  
  // Notification settings
  NOTIFICATION_SETTINGS_UPDATED: 'NOTIFICATION_SETTINGS_UPDATED',
  
  // Account lockout
  ACCOUNT_LOCKED: 'ACCOUNT_LOCKED',
  ACCOUNT_UNLOCKED: 'ACCOUNT_UNLOCKED',
  ACCOUNT_UNLOCKED_BY_ADMIN: 'ACCOUNT_UNLOCKED_BY_ADMIN',
} as const

export type AuditAction = typeof AUDIT_ACTIONS[keyof typeof AUDIT_ACTIONS]

// Entity types
export const ENTITY_TYPES = {
  USER: 'User',
  CHORE_TEMPLATE: 'ChoreTemplate',
  CHORE_ASSIGNMENT: 'ChoreAssignment',
  RECURRING_CHORE: 'RecurringChore',
  CHORE_OCCURRENCE: 'ChoreOccurrence',
  POINT_TRANSACTION: 'PointTransaction',
  PAYOUT: 'Payout',
  FAMILY: 'Family',
  POCKET_MONEY_CONFIG: 'PocketMoneyConfig',
  NOTIFICATION_SETTINGS: 'NotificationSettings',
} as const

export type EntityType = typeof ENTITY_TYPES[keyof typeof ENTITY_TYPES]
